# argocd-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-dash
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/a1mart/k8sdash.git'  # Use HTTPS for better compatibility
    targetRevision: HEAD
    path: k8s/chart
    helm:
      valueFiles:
        - values.yaml
      parameters:
        # Environment-specific overrides
        - name: env.NEXTAUTH_URL
          value: "https://k8s-dash.yourdomain.com"  # Update with your actual domain
        - name: env.KEYCLOAK_ISSUER
          value: "http://10.0.0.10:30786/realms/alm"
        - name: env.NEXT_PUBLIC_KEYCLOAK_URL
          value: "http://10.0.0.10:30786"
        - name: env.NEXT_PUBLIC_KEYCLOAK_REALM
          value: "alm"
        - name: env.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
          value: "k8s-dashboard"
        # Secrets - consider using sealed-secrets or external-secrets instead
        - name: secrets.NEXTAUTH_SECRET
          value: "your-super-secure-32-character-secret-key-here"
        - name: secrets.KEYCLOAK_CLIENT_ID
          value: "k8s-dashboard"
        - name: secrets.KEYCLOAK_CLIENT_SECRET
          value: "your-keycloak-client-secret"
        # Image tag (will be updated by CI/CD)
        - name: image.tag
          value: "latest"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: k8s-dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m