apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-dash
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: admin
    server: https://kubernetes.default.svc
  source:
    path: k8s/chart
    repoURL: https://github.com/a1mart/homepage
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: env.NEXTAUTH_URL
          value: http://10.0.0.216 
        - name: env.KEYCLOAK_ISSUER
          value: http://10.0.0.10:30786/realms/alm
        - name: env.NEXT_PUBLIC_KEYCLOAK_URL
          value: http://10.0.0.10:30786
        - name: env.NEXT_PUBLIC_KEYCLOAK_REALM
          value: alm
        - name: env.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
          value: k8s-dashboard
        - name: secrets.NEXTAUTH_SECRET
          value: your-random-secret-string
        - name: secrets.KEYCLOAK_CLIENT_ID
          value: k8s-dashboard
        - name: secrets.KEYCLOAK_CLIENT_SECRET
          value: nPwN7HpfAEbW3D6heshPP85wOXWWQMHl
        - name: image.tag
          value: latest
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m